CREATE TABLE contatos (
    id SERIAL PRIMARY KEY AUTO_INCREMENT,
    sala VARCHAR(100) NOT NULL,
    descricao VARCHAR(100) NOT NULL UNIQUE,
    nome VARCHAR(15),
    dataehora VARCHAR(100) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);